### ISSUE TITLE
Match and activeClassName not working on page load.

### ISSUE THREAD

**Issue by andres314** [preactjs/preact-router#412]
I'm using custom history with "createHashHistory" and the page URL is something like "example.com/dash?id=3&token=tokenValue". When the page load <Match> and activeClassName from <Link> doesn't workg but as soon as navigate through the menu start working. Also, the back and forward from the brower it's a little bit buggy, while the URL is updated, Match, activeClassName and the router don't always work as expected.

**Comment by developit** [comment]
Can you re-test this with the recently-released preact-router version 4?

**Comment by orangecoloured** [comment]
I'm using the version 4 and neither Match nor Link don't work.

Here are the `RouterOnChangeArgs`
<img width="894" alt="Screenshot 2022-01-18 at 9 00 18 PM" src="https://user-images.githubusercontent.com/3314891/150001588-566cd229-8678-4d23-b66c-f11ec83694cf.png">
.

**Comment by developit** [comment]
The initial page load issue _may_ be addressed via #416. The activeClassName and Match usage should be fixed by #416 though.

**Comment by andres314** [comment]
Sorry I didn't reply but I due to the lack of response and requirement was pretty simple I opted for using a custom solution for the router. Thanks anyway.

**Comment by orangecoloured** [comment]
I've just tested and it's working. No need to put a component inside a router anymore to use `useRouter` and the `activeClassName` works properly.

**Comment by ArcadeRenegade** [comment]
I am still seeing this behavior in v4.1.0

`activeClassName` does not work for a `default` route on page load.
